name: Generate Doxygen Docs

on:
  pull_request:
    branches:
      - main

jobs:
  doxygen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Generate Documentation
        run: doxygen Doxyfile

      - name: Upload Documentation as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-docs
          path: docs/html
